[0m17:44:22.069455 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d40830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106b16240>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106342240>]}


============================== 17:44:22.071381 | 90283d98-c68c-44c7-a9ad-9f424b563c5b ==============================
[0m17:44:22.071381 [info ] [MainThread]: Running with dbt=1.9.2
[0m17:44:22.071646 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '..', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt docs generate --profiles-dir ..', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m17:44:22.071862 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/fauzan/nrs/git/regentmarkets/dbt-exploration/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:44:22.072498 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.05273517, "process_in_blocks": "0", "process_kernel_time": 0.121281, "process_mem_max_rss": "91734016", "process_out_blocks": "0", "process_user_time": 0.595693}
[0m17:44:22.072679 [debug] [MainThread]: Command `dbt docs generate` failed at 17:44:22.072642 after 0.05 seconds
[0m17:44:22.072822 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d40830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102f9eb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e77f20>]}
[0m17:44:22.072946 [debug] [MainThread]: Flushing usage events
[0m17:44:22.629041 [debug] [MainThread]: An error was encountered while trying to flush usage events
